micronaut.application.name=findAds
micronaut.security.endpoints.login.enabled=false
micronaut.security.endpoints.oauth.enabled=false

micronaut.security.authentication=cookie
micronaut.security.token.cookie.cookie-name=access_token

datasources.default.url=${DB_URL}
datasources.default.username=${DB_USERNAME}
datasources.default.password=${DB_PASSWORD}
datasources.default.driverClassName=org.postgresql.Driver

micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_SECRET}
micronaut.security.token.generator.access-token.expiration=${JWT_ACCESS_EXPIRATION:900}
micronaut.security.token.jwt.generator.refresh-token.enabled=true
micronaut.security.token.jwt.generator.refresh-token.secret="${JWT_SECRET}"

micronaut.security.cookie.secure=${COOKIE_SECURE:false}

flyway.datasources.default.enabled=true
flyway.datasources.default.baseline-on-migrate=true

logger.levels.io.micronaut.flyway=DEBUG