micronaut.application.name=findAds
micronaut.server.port=${PORT:8080}

micronaut.security.enabled=true
micronaut.security.authentication=cookie
micronaut.security.token.jwt.enabled=true
micronaut.security.endpoints.login.enabled=false

micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_SECRET}
micronaut.security.token.jwt.generator.refresh-token.secret=${JWT_SECRET}

micronaut.security.token.generator.access-token.expiration=900
micronaut.security.token.cookie.enabled=true
micronaut.security.token.cookie.cookie-name=access_token

micronaut.security.token.jwt.generator.refresh-token.enabled=true
micronaut.security.token.refresh.cookie.enabled=true
micronaut.security.token.refresh.cookie.cookie-name=refresh_token

datasources.default.url=${DB_URL}
datasources.default.username=${DB_USERNAME}
datasources.default.password=${DB_PASSWORD}
datasources.default.driverClassName=org.postgresql.Driver

flyway.datasources.default.enabled=true
flyway.datasources.default.baseline-on-migrate=true

logger.levels.io.micronaut.flyway=DEBUG