micronaut.application.name=findAds
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/find-my-ads
datasources.default.username=postgres
datasources.default.password=postgres
datasources.default.driverClassName=org.postgresql.Driver

flyway.datasources.default.enabled=true
flyway.datasources.default.baseline-on-migrate=true

logger.levels.io.micronaut.flyway=DEBUG

micronaut.security.authentication=bearer
micronaut.security.token.jwt.signatures.secret.generator.secret="${JWT_GENERATOR_SIGNATURE_SECRET:test-secret-key-1234567890abcdefghijklmnopqrstuvwxyz}"'
micronaut.security.token.generator.access-token.expiration=300
micronaut.security.token.jwt.generator.refresh-token.enabled=true
micronaut.security.token.jwt.generator.refresh-token.secret="${JWT_GENERATOR_SIGNATURE_SECRET:test-secret-key-1234567890abcdefghijklmnopqrstuvwxyz}"'
